name: query_builder
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.14.0 <4.0.0"

dependencies:
  dart_style: ^2.0.0
  petitparser: ^5.0.0
  oxidized: ">=5.0.1 <7.0.0"

dev_dependencies:
  lint: ^2.0.0
  test: ^1.16.0
