name: query_builder_generator
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  build: ^2.4.2
  source_gen: ^2.0.0
  analyzer: ">=7.4.5"
  query_builder:
    path: ../

dev_dependencies:
  build_runner: ^2.4.15
  build_config: ^1.1.2
  test: ^1.26.2
